#!/bin/sh
# render-config.sh — turn environment variables into the TOML config file that
# Thunderbottom/umami-alerts expects (it has no env-var support of its own).
#
# Field names below MUST match the upstream serde structs exactly:
#   [smtp]    host, port, username, password, from, tls, timeout_seconds, skip_verify
#   [websites.<key>]  id, name, base_url, username, password, recipients, timezone, disabled
#   [app]     debug, dry_run, max_concurrent_jobs, report_type
#
# Writes to $CONFIG_PATH (default /app/config.toml). Fails fast with a clear
# message if a required value is missing.
set -eu

CONFIG_PATH="${CONFIG_PATH:-/app/config.toml}"

die() {
    echo "render-config: ERROR: $*" >&2
    exit 1
}

# Lowercase a value to a strict TOML boolean (true/false).
toml_bool() {
    case "$(printf '%s' "${1:-}" | tr '[:upper:]' '[:lower:]')" in
        1|true|yes|on)  echo "true" ;;
        *)              echo "false" ;;
    esac
}

# Escape a value for use inside a TOML basic ("...") string.
esc() {
    # backslash first, then double-quote
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# Turn a comma-separated list into a TOML array of quoted, trimmed strings:
#   "a@x.com, b@x.com" -> "a@x.com", "b@x.com"
toml_str_array() {
    _list="$1"
    _out=""
    # POSIX field-splitting on comma
    _old_ifs="$IFS"
    IFS=','
    for _item in $_list; do
        # trim leading/trailing whitespace
        _item="$(printf '%s' "$_item" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
        [ -z "$_item" ] && continue
        if [ -z "$_out" ]; then
            _out="\"$(esc "$_item")\""
        else
            _out="$_out, \"$(esc "$_item")\""
        fi
    done
    IFS="$_old_ifs"
    printf '[%s]' "$_out"
}

# --- Required: email + SMTP password ----------------------------------------
SMTP_PASSWORD_EFFECTIVE="${SMTP_PASSWORD:-${RESEND_API_KEY:-}}"
[ -n "${SMTP_PASSWORD_EFFECTIVE}" ] || \
    die "set RESEND_API_KEY (or SMTP_PASSWORD) — used as the SMTP password"
[ -n "${EMAIL_FROM:-}" ] || \
    die "set EMAIL_FROM — the From address, e.g. 'Umami Reports <reports@you.com>'"

# --- [smtp] / [app] defaults -------------------------------------------------
SMTP_HOST="${SMTP_HOST:-smtp.resend.com}"
SMTP_PORT="${SMTP_PORT:-587}"
SMTP_USERNAME="${SMTP_USERNAME:-resend}"
SMTP_TLS="$(toml_bool "${SMTP_TLS:-true}")"
SMTP_SKIP_VERIFY="$(toml_bool "${SMTP_SKIP_VERIFY:-false}")"
SMTP_TIMEOUT="${SMTP_TIMEOUT:-30}"

APP_DEBUG="$(toml_bool "${DEBUG:-false}")"
APP_DRY_RUN="$(toml_bool "${DRY_RUN:-false}")"
APP_MAX_JOBS="${MAX_CONCURRENT_JOBS:-4}"
APP_REPORT_TYPE="${REPORT_TYPE:-daily}"
case "$APP_REPORT_TYPE" in
    daily|weekly) ;;
    *) die "REPORT_TYPE must be 'daily' or 'weekly' (got '$APP_REPORT_TYPE')" ;;
esac

# --- write the top of the file ----------------------------------------------
{
    echo "# Generated by render-config.sh — do not edit by hand."
    echo "# All values come from environment variables."
    echo
    echo "[app]"
    echo "debug = ${APP_DEBUG}"
    echo "dry_run = ${APP_DRY_RUN}"
    echo "max_concurrent_jobs = ${APP_MAX_JOBS}"
    echo "report_type = \"$(esc "$APP_REPORT_TYPE")\""
    echo
    echo "[smtp]"
    echo "host = \"$(esc "$SMTP_HOST")\""
    echo "port = ${SMTP_PORT}"
    echo "username = \"$(esc "$SMTP_USERNAME")\""
    echo "password = \"$(esc "$SMTP_PASSWORD_EFFECTIVE")\""
    echo "from = \"$(esc "$EMAIL_FROM")\""
    echo "tls = ${SMTP_TLS}"
    echo "skip_verify = ${SMTP_SKIP_VERIFY}"
    echo "timeout_seconds = ${SMTP_TIMEOUT}"
    echo
} > "$CONFIG_PATH"

# --- websites ----------------------------------------------------------------
# Emit one [websites.<key>] block. Shared helper used by both the single-site
# and the numbered SITE_N_* paths.
emit_site() {
    _key="$1"; _id="$2"; _name="$3"; _base_url="$4"
    _user="$5"; _pass="$6"; _recipients="$7"; _tz="$8"

    [ -n "$_base_url" ]   || die "site '$_key': missing base_url"
    [ -n "$_id" ]         || die "site '$_key': missing website id"
    [ -n "$_user" ]       || die "site '$_key': missing username"
    [ -n "$_pass" ]       || die "site '$_key': missing password"
    [ -n "$_recipients" ] || die "site '$_key': missing recipients"

    {
        echo "[websites.${_key}]"
        echo "id = \"$(esc "$_id")\""
        echo "name = \"$(esc "${_name:-$_key}")\""
        echo "base_url = \"$(esc "$_base_url")\""
        echo "username = \"$(esc "$_user")\""
        echo "password = \"$(esc "$_pass")\""
        echo "recipients = $(toml_str_array "$_recipients")"
        echo "timezone = \"$(esc "${_tz:-UTC}")\""
        echo "disabled = false"
        echo
    } >> "$CONFIG_PATH"
}

SITE_COUNT=0

# Numbered multi-site path: SITE_1_*, SITE_2_*, … Present if SITE_1_BASE_URL set.
n=1
while :; do
    eval "_bu=\${SITE_${n}_BASE_URL:-}"
    [ -n "${_bu}" ] || break
    eval "_id=\${SITE_${n}_WEBSITE_ID:-}"
    eval "_nm=\${SITE_${n}_NAME:-}"
    eval "_us=\${SITE_${n}_USERNAME:-}"
    eval "_pw=\${SITE_${n}_PASSWORD:-}"
    eval "_rc=\${SITE_${n}_RECIPIENTS:-}"
    eval "_tz=\${SITE_${n}_TIMEZONE:-${TIMEZONE:-UTC}}"
    emit_site "site${n}" "$_id" "$_nm" "$_bu" "$_us" "$_pw" "$_rc" "$_tz"
    SITE_COUNT=$((SITE_COUNT + 1))
    n=$((n + 1))
done

# Single-site path (only when no numbered sites were provided).
if [ "$SITE_COUNT" -eq 0 ]; then
    [ -n "${UMAMI_BASE_URL:-}" ] || \
        die "no sites configured — set UMAMI_BASE_URL (+ id/user/pass/recipients) or SITE_1_*"
    emit_site "site" \
        "${UMAMI_WEBSITE_ID:-}" \
        "${SITE_NAME:-}" \
        "${UMAMI_BASE_URL:-}" \
        "${UMAMI_USERNAME:-}" \
        "${UMAMI_PASSWORD:-}" \
        "${REPORT_RECIPIENTS:-}" \
        "${TIMEZONE:-UTC}"
    SITE_COUNT=1
fi

echo "render-config: wrote ${CONFIG_PATH} (${SITE_COUNT} site(s))" >&2

# When debugging, echo the config with the SMTP password masked.
if [ "$APP_DEBUG" = "true" ]; then
    echo "render-config: --- ${CONFIG_PATH} (password masked) ---" >&2
    sed 's/^password = .*/password = "***"/' "$CONFIG_PATH" >&2
    echo "render-config: --- end ---" >&2
fi
